.gitignore, xivo_confgen/plugins/pjsip_conf.py
gitignore: add egg-info
pjsip: convert application to context
=> Pull request for WAZO-891-line-application

Dockerfile, debian/wazo-confgend.postinst, debian/wazo-confgend.service
since buster /var/run is a now a symlink to /run
=> use /run instead of /var/run

wazo_confgend/helpers/asterisk.py, wazo_confgend/plugins/pjsip_conf.py, wazo_confgend/plugins/pjsip_options.py
this section of the configuration is now in the asterisk_file tables with all
the logic in the API and in the AsteriskFileGenerator class.
=> pjsip global: pjsip.conf global is now in the asterisk_file DB

wazo_confgend/plugins/pjsip_conf.py, wazo_confgend/plugins/pjsip_options.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/35
=> Wazo 1612 pjsip: generate the system section from asterisk_file table

requirements.txt, wazo_confgend/plugins/pjsip_conf.py, wazo_confgend/plugins/pjsip_options.py, wazo_confgend/plugins/tests/test_pjsip_conf.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/37
=> WAZO-1613 pjsip: generate transports from the DB

wazo_confgend/plugins/pjsip_conf.py, wazo_confgend/plugins/pjsip_registration.py, wazo_confgend/plugins/tests/test_pjsip_conf.py
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1740
=> PJSIP: use the configured transport instead of constructing a name

debian/wazo-confgend.service, wazo_confgend/bin/daemon.py
debian: add syslogidentifier
run always in foreground
=> Pull request for WAZO-1762-foreground

wazo_confgend/confgen.py, wazo_confgend/plugins/provd_conf.py
reason: to avoid commit new value in the database
=> use session_scope with read_only

wazo_confgend/generators/sccp.py, wazo_confgend/generators/tests/test_sccp.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/101
=> WAZO-2059-refactor-online-call-record

wazo_confgend/generators/tests/expected_generated_extension.conf, wazo_confgend/generators/tests/test_extensionsconf.py, wazo_confgend/hints/adaptor.py, wazo_confgend/hints/tests/test_adaptor.py, wazo_confgend/hints/tests/test_generator.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/111
=> fix hints for confbridge funckey

wazo_confgend/generators/queues.py, wazo_confgend/generators/tests/test_queues.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/121
=> Nes 906 group name

wazo_confgend/hints/generator.py, wazo_confgend/hints/tests/test_generator.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/135
=> remove "TODO clean after pjsip migration"

wazo_confgend/templates/asterisk/extensions/meeting-guest.jinja, wazo_confgend/templates/asterisk/extensions/meeting-user.jinja, wazo_confgend/tests/test_template.py
Why:
* Necessary for nice call logs
=> meetings: add meeting name variable

etc/wazo-confgend/templates/contexts.conf, wazo_confgend/generators/extensionsconf.py, wazo_confgend/generators/tests/expected_generated_extension.conf, wazo_confgend/generators/tests/test_extensionsconf.py, wazo_confgend/templates/asterisk/extensions/meeting-guest.jinja, wazo_confgend/templates/asterisk/extensions/meeting-user.jinja, wazo_confgend/tests/test_template.py
Depends-On: https://github.com/wazo-platform/xivo-config/pull/60/files
=> WAZO-2577 WP-445 meeting creation optimization

wazo_confgend/plugins/confbridge_conf.py
when the 26th user enters the meeting the "sound_locked" is played.
=> meeting: make the max number of participants 25

etc/wazo-confgend/templates/contexts.conf, wazo_confgend/generators/extensionsconf.py, wazo_confgend/generators/tests/expected_generated_extension.conf, wazo_confgend/generators/tests/test_extensionsconf.py
=> Pull request for WAZO-2847-internal-tenant-uuid

wazo_confgend/plugins/features_conf.py
For consistency with rest of code base.
=> Changed FeaturesConfGenerator instance logger into module logger

wazo_confgend/templates/asterisk/extensions/ivr.jinja
Adding new CELGenUserEvent WAZO_IVR_CHOICE to store DTMF choices in IVR.
=> CELGenUserEvent for storing DTMF choices in IVR 

wazo_confgend/plugins/provd_conf.py, wazo_confgend/plugins/tests/test_provd_conf.py
why: they were redundant options
=> provd: merge host and http_port to http_base_url

integration_tests/suite/test_confgen.py, wazo_confgend/asterisk.py, wazo_confgend/generators/queues.py, wazo_confgend/tests/test_asterisk.py
why: impossible to configure since 18.03
=> remove unused queues penalties system

debian/wazo-confgend.dirs, etc/rsyslog.d/99-wazo-confgend.conf
=> WAZO-3682: disable logs to rsyslog

.pre-commit-config.yaml, Dockerfile, README.md, debian/control, integration_tests/assets/docker-compose.yml, pyproject.toml, requirements.txt, test-requirements.txt, tox.ini, zuul.yaml
Depends-on: https://github.com/wazo-platform/wazo-confgend-client/pull/15
- **upgrade bookworm**
- **README: fix styling**
- **upgrade python dependencies to bookworm version**
=> WAZO-4279-bookworm
