debian/wazo-confgend.postinst

Find tries to move files after moving directories, and moving
directories previously moved those files.

debian: fix cache files move in postinst

---

test-requirements.txt
wazo_confgend/generators/extensionsconf.py

The python configparser is now ordered by default, no need to
use the backported hacked python 2.4 module.
See: https://www.python.org/dev/peps/pep-0372/

Use python configparser

---

wazo_confgend/plugins/pjsip_conf.py
wazo_confgend/plugins/pjsip_options.py

The goal is to be able to generate this configuration
```
[wazo-general-registration](!)
type = registration
retry_interval = 20
auth_rejection_permanent = off
forbidden_retry_interval = 30
fatal_retry_interval = 30
max_retries = 10000
```

pjsip: add some options to the registration section

---

wazo_confgend/generators/extensionsconf.py
wazo_confgend/generators/tests/test_extensionsconf.py
wazo_confgend/template.py
wazo_confgend/tests/test_template.py

The problem here is that the current version mixes unicode and str in the StringIO object.
`template.generate` encodes the template in utf8 and adds it the StringIO which already contains unicode. the `template.dump` method already render the template without encoding it.

Wazo 1435 none ascii ivr sound files

---

wazo_confgend/templates/asterisk/extensions/ivr.jinja
wazo_confgend/tests/test_template.py

";" is the beginning of a comment in Asterisk dialplan. The AGI parses
actionarg2 splitting values separated by ";". To be able to output a Gosub with
";" in its parameters we have to escape the ";" using "\;".

ivr: escape ";" in actionarg2

---

etc/wazo-confgend/templates/contexts.conf
wazo_confgend/generators/extensionsconf.py
wazo_confgend/generators/tests/expected_generated_extension.conf
wazo_confgend/generators/tests/test_extensionsconf.py

Why:
* called party may want to know which extension was dialed, e.g. a user
with multiple DID

contexts: inherit BASE_EXTEN and BASE_CONTEXT variables

---

etc/wazo-confgend/config.yml
wazo_confgend/config.py

why: used for traceability
replace: https://github.com/wazo-platform/xivo-dao/pull/23

set pg application_name

---

wazo_confgend/generators/extensionsconf.py
wazo_confgend/generators/tests/expected_generated_extension.conf
wazo_confgend/generators/tests/test_extensionsconf.py
wazo_confgend/hints/tests/test_adaptor.py
wazo_confgend/hints/tests/test_generator.py
wazo_confgend/plugins/confbridge_conf.py
wazo_confgend/plugins/pjsip_conf.py
wazo_confgend/plugins/tests/test_pjsip_conf.py
wazo_confgend/templates/asterisk/extensions/meeting-guest.jinja
wazo_confgend/templates/asterisk/extensions/meeting-user.jinja
wazo_confgend/tests/test_template.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/137
Why:
* contains() is deprecated in favor of contains_exactly()

Pull request for WAZO-2518-meetings

---

etc/wazo-confgend/config.yml

why: it depends from res_phoneprov module which is already disabled
Adding explicit disable will remove error log at asterisk boot

disable pjsip_phoneprov_provider module

---

wazo_confgend/plugins/provd_conf.py
wazo_confgend/plugins/tests/test_provd_conf.py

I am reviving this OLD branch that was forgotten. Without this, the provisioning port section in the provd API (and in confd) is useless since the configuration file is not generated.

[WAZO-2772] provd network: extract more values from the database

---

wazo_confgend/generators/tests/test_voicemail.py
wazo_confgend/generators/voicemail.py

reason: Crashes if non ASCII characters are included

Fixes encoding issue with Python2 unicodes in voicemail.py

---

Dockerfile
requirements.txt
tox.ini

How:
* Twisted seems to download the latest version of the lib "incremental"
by itself, without regards for the constraints in requirements.txt.
* When installing typing from requirements.txt, Twisted loads
"incremental" before typing is even installed by pip

docker: fix building image

---

requirements.txt

why: twisted require unpinned automat version and this library has
released a new version (22.10.0) which is incompatible with python2
That's why we pin automat to buster version

pin automat dependency to support python2

---

debian/wazo-confgend.maintscript

debian: remove unused maintscript

---

wazo_confgend/plugins/tests/test_musiconhold.py
wazo_confgend/templates/asterisk/musiconhold.jinja

Why:
* The database entries for the default MOH are corrupt (tenant UUID
inexisting), we can't rely on them for now.

moh: hardcode default class

---

wazo_confgend/generators/extensionsconf.py

calling Pickup here does not allow me to add logic for the dial_mobile scenario which is a stasis application that does not behave correctly with the Pickup application.
Depends-On: https://github.com/wazo-platform/xivo-config/pull/89

pickup: add dialplan around the Pickup application

---

wazo_confgend/hints/adaptor.py
wazo_confgend/hints/tests/test_adaptor.py

the hints functions in the dao now return a dict of context/hints
this change makes it possible top query the DB only once for each hint type when generating the dialplan and reuse the same result for each context being generated.

WAZO-3605-slow-extensions.conf

---

wazo_confgend/generators/tests/test_queues.py

why: this was removed from xivo-dao and is breaking tests

generators.tests: fixed obsolete find_queue_penalty_settings mock

---

Dockerfile

Why:
* Latest version of incremental is downloaded by twisted at install
time
* Latest version of incremental is incompatible with setuptools 58

Dockerfile: pin version of twisted dependency

---

wazo_confgend/generators/res_parking.py
wazo_confgend/generators/tests/test_res_parking.py

Why:
* The default parking lot will override any extension between 700 and
750

parking: disable default parking lot

---

Dockerfile

why: without MANIFEST.in the templates directory was not included
Since bump of jinja2 version, an error was shown during the start of
the service

Dockerfile: include templates directory in image

---

etc/wazo-confgend/config.yml

we have a bug that prevent asterisk from start when starting res_freeze_check

disable res_freeze_check

---

etc/wazo-confgend/config.yml

Reverts wazo-platform/wazo-confgend#122
This should be done after merging the res-freeze-check fix: https://github.com/wazo-platform/xivo-res-freeze-check/pull/14

Revert "disable res_freeze_check"

---

wazo_confgend/plugins/modules_conf.py

enabled_asterisk_modules actually are disabled_asterisk_modules,
for which a "noload" is generated in the modules.conf

modules_conf: fix confusion variable name
